#!/usr/bin/env bash
set -e
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.13.1.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.13.1.html
pip install git+https://github.com/pyg-team/pytorch_geometric.git
mkdir -p /opt
cd /opt